import test from 'node:test';
import assert from 'node:assert/strict';
import {prepareAssistant,assistantAction,assistantCapabilities,returnAssistantResult,approvedAssistantPlan} from '../supabase/functions/studkab-requests/assistant-service.mjs';
import {collectAssistantBundle,digest,verifyAssistantManifest} from '../supabase/functions/_shared/assistant-bundle.mjs';
const R='11111111-1111-4111-8111-111111111111',A='22222222-2222-4222-8222-222222222222',F='33333333-3333-4333-8333-333333333333',P='44444444-4444-4444-8444-444444444444',J='55555555-5555-4555-8555-555555555555',C='66666666-6666-4666-8666-666666666666';
const user={id:A,email:'executor@example.test'},input={id:R,provider:'claude',operation:P},bytes=new TextEncoder().encode('Задание');
async function source(){const request={id:R,revision:2,ready_at:'yes',payload:{route:'r3',k:'Практическая',d:'Экономика',n:'Студент',u:'Вуз',org:'Все сведения',cn:'Контакт'}};const attachments=[{id:F,request_id:R,file_name:'Задание.txt',content_type:'text/plain',file_hash:await digest(bytes),size_bytes:bytes.length,storage_path:R+'/file'}];const context={passports:[{id:P,status:'approved',revision:1,items:[{id:'STRUCTURE',text:'Ответ',verified:true}],material_manifest:{requirements:[]}}],materialRevisions:[{state:'locked',revision:2}],answers:[{id:F,question:'Данные?',answer:'Полный ответ',answer_source:'Студент'}],returnAt:null};return {request,attachments,attachmentsComplete:true,context,basis:{payload:request.payload,revision:2,attachments,context}};}
async function fixture(overrides={}){const s=await source(),calls=[];let snapshot;return {s,calls,get snapshot(){return snapshot},deps:{config:async()=>({executor_email:user.email}),loadRequestFile:async()=>bytes,planSections:async()=>['answer'],rpc:async(name,args)=>{calls.push([name,args]);if(name==='studkab_assistant_snapshot')return s;if(name==='studkab_material_manifest_check')return {valid:true};if(name==='studkab_assistant_accept'){snapshot=args.p_snapshot;return {jobId:J,state:'prepared',acceptedAt:'2026-10-09T01:00:00Z'};}if(name==='studkab_assistant_state')return {job:null,work:null};throw Error('Unexpected RPC '+name);},...overrides}};}
test('acceptance snapshots all server context and bytes, freezes plan, and returns system receipt only',async()=>{const f=await fixture();const r=await prepareAssistant(input,user,f.deps);assert.equal(r.state,'prepared');assert.equal(r.receipt.files.length,1);assert.equal(f.snapshot.schema,2);assert.equal(f.snapshot.context.answers[0].answer,'Полный ответ');assert.equal(f.snapshot.context.payload.org,'Все сведения');assert.ok(f.snapshot.context.passports[0].material_manifest);assert.equal(f.snapshot.files[0].bytes,undefined);await verifyAssistantManifest(f.snapshot);const accept=f.calls.find(c=>c[0]==='studkab_assistant_accept')[1];assert.deepEqual(accept.p_basis,f.s.basis);assert.deepEqual(accept.p_sections,['answer']);assert.equal(accept.p_operation,P);});
test('complete context changes fingerprint and post-collection mutation is rejected',async()=>{const s=await source();const b=await collectAssistantBundle({...s,provider:'chatgpt'},{loadRequestFile:async()=>bytes});const s2=await source();s2.context.answers[0].answer='Другой полный ответ';const b2=await collectAssistantBundle({...s2,provider:'chatgpt'},{loadRequestFile:async()=>bytes});assert.notEqual(b.fingerprint,b2.fingerprint);b.context.passports[0].items[0].text='Подмена';await assert.rejects(verifyAssistantManifest(b),/BUNDLE_CHANGED/);});
test('partial snapshots and incomplete context never write acceptance',async()=>{for(const change of [s=>s.attachmentsComplete=false,s=>delete s.context.answers]){const f=await fixture();change(f.s);await assert.rejects(prepareAssistant(input,user,f.deps),/INCOMPLETE_SNAPSHOT|PASSPORT_REQUIRED/);assert.equal(f.calls.some(c=>c[0]==='studkab_assistant_accept'),false);}});
test('R3 complete kit capture does not add old passport gate; missing server plan stays explicit',async()=>{const f=await fixture({planSections:null});f.s.context.passports=[];const r=await prepareAssistant({...input,sections:['invented']},user,f.deps);assert.equal(r.planReady,false);assert.deepEqual(f.calls.find(c=>c[0]==='studkab_assistant_accept')[1].p_sections,[]);assert.equal(f.calls.some(c=>c[0]==='studkab_material_manifest_check'),false);});
test('race rejection never produces acceptance receipt',async()=>{const f=await fixture();const rpc=f.deps.rpc;f.deps.rpc=async(n,a)=>n==='studkab_assistant_accept'?{error:'MATERIALS_CHANGED'}:rpc(n,a);await assert.rejects(prepareAssistant(input,user,f.deps),/MATERIALS_CHANGED/);});
test('capabilities never invent an installed model and paid start writes nothing',async()=>{assert.ok(assistantCapabilities().providers.every(p=>p.available===false));const f=await fixture();const r=await assistantAction({...input,action:'assistant-start'},user,f.deps);assert.equal(r.status,409);assert.equal(r.data.error,'PROVIDER_NOT_CONNECTED');assert.deepEqual(f.calls,[]);});
test('student cannot accept/review; state reads pass actor to authoritative role projection',async()=>{const f=await fixture();assert.equal((await assistantAction({...input,action:'assistant-prepare'},{id:F,email:'student@example.test'},f.deps)).status,403);const r=await assistantAction({id:R,action:'assistant-state'},{id:F,email:'student@example.test'},f.deps);assert.deepEqual(r.data,{job:null,work:null});assert.equal(f.calls[0][1].p_actor,F);});
test('return loads stored manifest and uses atomic claim/commit adapters; storage failure is recovered',async()=>{const s=await source(),b=await collectAssistantBundle({...s,provider:'claude'},{loadRequestFile:async()=>bytes});const snapshot={...b,files:b.files.map(({bytes,...f})=>f)};const response={status:'completed',jobId:J,requestId:R,revision:2,provider:'claude',fingerprint:b.fingerprint,sections:[{id:'answer',name:'Ответ',text:'Полное решение'}]};const calls=[];let saved;
const rpc=async(n,a)=>{calls.push([n,a]);if(n==='studkab_assistant_return_snapshot')return {snapshot,response};if(n==='studkab_assistant_begin_return')return {allowed:true,claim:C,expectedSections:['answer']};if(n==='studkab_assistant_commit_return')return {ok:true};if(n==='studkab_assistant_fail_return')return {ok:true};throw Error(n);};
const result=await returnAssistantResult(J,A,response,{rpc,saveResult:async(...args)=>saved=args});assert.equal(result.requiresReview,true);assert.ok(saved[2].length>0);assert.equal(calls.find(c=>c[0]==='studkab_assistant_commit_return')[1].p_claim,C);
calls.length=0;await assert.rejects(returnAssistantResult(J,A,response,{rpc,saveResult:async()=>{throw Error('STORAGE_UNAVAILABLE')}}),/STORAGE_UNAVAILABLE/);assert.equal(calls.at(-1)[0],'studkab_assistant_fail_return');assert.equal(calls.some(c=>c[0]==='studkab_assistant_commit_return'),false);
});
test('review records hash with server ownership and does not transmit/deliver',async()=>{const calls=[];const f=await fixture({rpc:async(n,a)=>{calls.push([n,a]);return {ok:true,reviewedAt:'now'}}});const r=await assistantAction({action:'assistant-review',jobId:J,hash:'a'.repeat(64)},user,f.deps);assert.equal(r.data.ok,true);assert.deepEqual(calls,[['studkab_assistant_review',{p_job:J,p_actor:A,p_hash:'a'.repeat(64)}]]);});
test('authoritative plan preserves explicit approved structure; ambiguous prose/defaults/duplicates fail closed',()=>{const passport={status:'approved',items:[{id:'STRUCTURE',verified:true,text:'Структура:\n1. Введение\n2. Основная часть\n2.1. Расчёты\n3. Источники'}]};assert.deepEqual(approvedAssistantPlan({},passport),['section_1','section_2','section_2_1','section_3']);for(const text of ['Введение, расчёты, источники','1. Ответ\n1. Другой ответ',''])assert.throws(()=>approvedAssistantPlan({},{...passport,items:[{...passport.items[0],text}]}),/PLAN_REQUIRED/);assert.throws(()=>approvedAssistantPlan({},{...passport,status:'draft'}),/PLAN_REQUIRED/);});
