import test from 'node:test';
import assert from 'node:assert/strict';
import {financeObservation,createFinanceSession} from '../assistant-finance-ui.mjs';
const at='2026-10-09T10:00:00Z';
const value={schema:1,checkedAt:at,application:{status:'blocked',availableMicrousd:0,currency:'USD',checkedAt:at},providers:[{provider:'deepseek',balance:{status:'verified',observedAt:at,checkedAt:at,balances:[{currency:'CNY',total:'12.34'},{currency:'USD',total:'0.9'}]},costs:{status:'unknown'}},{provider:'chatgpt',balance:{status:'verified',observedAt:at,checkedAt:at,balances:[{currency:'USD',total:'999'}]},costs:{status:'unknown',reason:'not_configured'}}]};
test('supplier balance is separate from application zero; unsupported wallets never acquire a fake amount',()=>{const v=financeObservation(value);assert.equal(v.application.availableMicrousd,0);assert.equal(v.providers.find(p=>p.provider==='deepseek').balance.balances[0].total,'12.34');assert.deepEqual(v.providers.find(p=>p.provider==='chatgpt').balance,{status:'unknown'});assert.equal(v.providers.find(p=>p.provider==='chatgpt').reportReason,'not_configured');});
test('malformed, duplicate and unknown monetary records cannot be shown as verified',()=>{for(const change of [{status:'unknown'},{balances:[{currency:'USD',total:'NaN'}]},{balances:[{currency:'USD',total:'1'},{currency:'USD',total:'2'}]}]){const v=structuredClone(value);Object.assign(v.providers[0].balance,change);assert.deepEqual(financeObservation(v).providers.find(p=>p.provider==='deepseek').balance,{status:'unknown'});}assert.throws(()=>financeObservation({}));});
test('refresh is read-only and duplicate presses coalesce; failure retains explicit stale data for at most ten minutes',async()=>{let resolve,fail=false,t=Date.parse(at);const calls=[];const session=createFinanceSession({api:i=>{calls.push(i);return fail?Promise.reject(Error('network')):new Promise(r=>resolve=r);},active:()=>true,onChange:()=>{},now:()=>t});const pending=session.refresh();await session.refresh();assert.equal(calls.length,1);assert.deepEqual(calls[0],{action:'assistant-finances'});resolve(value);await pending;t=Date.parse(at)+1;fail=true;await session.refresh();assert.equal(session.state.value.application.status,'unknown');assert.equal(session.state.value.providers.find(p=>p.provider==='deepseek').balance.status,'stale');t=Date.parse(at)+600001;await session.refresh();assert.equal(session.state.value,null);});
test('late response after close or changed identity cannot be published',async()=>{let active=true,resolve;const paints=[];const s=createFinanceSession({api:()=>new Promise(r=>resolve=r),active:()=>active,onChange:s=>paints.push(s.message)});const pending=s.refresh();active=false;resolve(value);await pending;assert.equal(s.state.value,null);assert.equal(paints.length,1);});
test('a scoped cost report keeps period and supplier coverage, discards all other data',()=>{const v=structuredClone(value);v.providers[1].costs={status:'verified',observedAt:at,checkedAt:at,amount:'1.23',currency:'USD',periodStart:'2026-10-01T00:00:00Z',periodEnd:at,key:'discard'};const c=financeObservation(v).providers.find(p=>p.provider==='chatgpt').costs;assert.equal(c.amount,'1.23');assert.equal(c.key,undefined);assert.equal(c.periodStart,'2026-10-01T00:00:00Z');});

test('failed refresh does not extend the age of a server-side stale observation',async()=>{let fail=false;const stale=structuredClone(value);stale.providers[0].balance.status='stale';let t=Date.parse(at)+590000;const s=createFinanceSession({api:async()=>{if(fail)throw Error('offline');return stale;},active:()=>true,onChange:()=>{},now:()=>t});await s.refresh();fail=true;t+=20000;await s.refresh();assert.deepEqual(s.state.value.providers.find(p=>p.provider==='deepseek').balance,{status:'unknown'});});
