import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {randomUUID} from 'node:crypto';
import {DOMParser} from '@xmldom/xmldom';
import {setupAssistantFixture} from './assistant-durable-fixture.mjs';
import {prepareAssistant,returnAssistantResult,assistantAction} from '../supabase/functions/studkab-requests/assistant-service.mjs';
import {digest} from '../supabase/functions/_shared/assistant-bundle.mjs';
import {readDocument} from '../supabase/functions/studkab-requests/structured-reader.mjs';
import {handler} from '../supabase/functions/studkab-requests/handler.mjs';
const actor=randomUUID(),student=randomUUID(),other=randomUUID(),user={id:actor,email:'executor@offline.test'};
const bytes=new TextEncoder().encode('Полный исходный документ');let db;
before(async()=>{db=new PGlite();await setupAssistantFixture(db,{actor,student,other});});after(async()=>db?.close());
const rpc=async(n,args)=>(await db.query('select public.'+n+'('+Object.keys(args).map((k,i)=>k+'=> $'+(i+1)).join(',')+') value',Object.values(args))).rows[0].value;
async function ready(withPlan=true){const id=randomUUID(),fid=randomUUID();await db.query('insert into studkab_requests(id,student_id,payload) values($1,$2,$3)',[id,student,{route:'r3',n:'Offline Student',u:'Offline University',k:'Практическая',d:'Экономика',rq:'Исходное задание'}]);await db.query('insert into studkab_request_attachments values($1,$2,$3,$4,$5,$6,$7,null)',[fid,id,'Задание.txt','text/plain',bytes.length,await digest(bytes),id+'/f']);await db.query('insert into studkab_clarifications values($1,$2,now(),$3)',[randomUUID(),id,'Ответ студента целиком']);const deps={rpc,loadRequestFile:async()=>bytes,...(withPlan?{planSections:async()=>['answer']}:{})};const input={id,provider:'deepseek',operation:randomUUID()};const accepted=await prepareAssistant(input,user,deps);return {id,input,accepted,deps};}
async function complete(k){const args={p_job:k.accepted.jobId,p_actor:actor};await rpc('studkab_assistant_queue',args);const claim=await rpc('studkab_assistant_claim',args);await rpc('studkab_assistant_dispatch',{...args,p_claim:claim.claim});const response={status:'completed',jobId:k.accepted.jobId,requestId:k.id,revision:k.accepted.receipt.revision,provider:'deepseek',fingerprint:k.accepted.receipt.fingerprint,sections:[{id:'work',name:'Работа',text:'Полный результат по документам'},{id:'commentary',name:'Комментарий',text:'Получен Задание.txt. Работа выполнена по комплекту.'}]};await rpc('studkab_assistant_complete',{...args,p_claim:claim.claim,p_response:response});return response;}
test('JS acceptance uses real SQL snapshot and idempotent receipt including lost-response alias lookup',async()=>{const k=await ready();assert.equal(k.accepted.state,'prepared');const alias=randomUUID();const again=await prepareAssistant({...k.input,operation:alias},user,k.deps);assert.equal(again.jobId,k.accepted.jobId);assert.equal(again.duplicate,true);const read=await assistantAction({action:'assistant-state',id:k.id,operation:alias},user,{...k.deps,config:async()=>({executor_email:user.email})});assert.equal(read.data.job.id,k.accepted.jobId);assert.equal(read.data.accepted,true);const stored=await rpc('studkab_assistant_return_snapshot',{p_job:k.accepted.jobId,p_actor:actor});assert.equal(stored.snapshot.context.answers[0].answer,'Ответ студента целиком');assert.equal(stored.snapshot.files.length,1);});
test('R3 originals acceptance and queue require no internal reading or passport',async()=>{const k=await ready(false);assert.equal(k.accepted.planReady,true);assert.equal((await rpc('studkab_assistant_queue',{p_job:k.accepted.jobId,p_actor:actor})).ok,true);});
test('real completed SQL job returns parseable Word atomically; review gates delivery and student projection',async()=>{const k=await ready(),response=await complete(k);let saved;const result=await returnAssistantResult(k.accepted.jobId,actor,response,{rpc,saveResult:async(...args)=>{saved=args}});assert.equal(result.requiresReview,true);const parsed=await readDocument(saved[2],saved[1],{DOMParser});assert.equal(parsed.status,'ready');assert.match(parsed.extracted_text,/Offline Student/);assert.match(parsed.extracted_text,/Полный результат/);await assert.rejects(rpc('studkab_r3_deliver',{p_request:k.id,p_hash:result.file.hash}),/ASSISTANT_REVIEW_REQUIRED/);await rpc('studkab_assistant_review',{p_job:k.accepted.jobId,p_actor:actor,p_hash:result.file.hash});const delivered=await rpc('studkab_r3_deliver',{p_request:k.id,p_hash:result.file.hash});assert.ok(!delivered.error);const st=await rpc('studkab_assistant_state',{p_request:k.id,p_actor:student});assert.equal(st.job.resultHash,null);assert.equal(st.work.result,null);assert.equal(st.work.delivered.name,result.file.name);assert.equal((await returnAssistantResult(k.accepted.jobId,actor,response,{rpc,saveResult:async()=>{throw Error('Must not resave')}})).duplicate,true);});
test('real SQL return recovers storage failure without new inference; different response cannot reuse completion',async()=>{const k=await ready(),response=await complete(k);await assert.rejects(returnAssistantResult(k.accepted.jobId,actor,response,{rpc,saveResult:async()=>{throw Error('STORAGE_DOWN')}}),/STORAGE_DOWN/);assert.equal((await rpc('studkab_assistant_state',{p_request:k.id,p_actor:actor})).job.state,'completed');await assert.rejects(returnAssistantResult(k.accepted.jobId,actor,{...response,sections:[{id:'answer',name:'Ответ',text:'Подмена'}]},{rpc,saveResult:async()=>{throw Error('Must not write')}}),/RESULT_RESPONSE_CHANGED/);await returnAssistantResult(k.accepted.jobId,actor,response,{rpc,saveResult:async()=>{}});assert.equal((await rpc('studkab_assistant_state',{p_request:k.id,p_actor:actor})).job.state,'returned');});
test('student-progress after real R3 return suppresses old download proof without exposing executor file',async()=>{const k=await ready(false),hash=await digest(bytes);await rpc('studkab_r3_take',{p_request:k.id});await rpc('studkab_r3_result_set',{p_request:k.id,p_name:'Work.docx',p_type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',p_size:bytes.length,p_hash:hash,p_path:'r3-results/'+k.id+'/'+hash});await rpc('studkab_r3_deliver',{p_request:k.id,p_hash:hash});await rpc('studkab_r3_downloaded',{p_request:k.id,p_student:student});await rpc('studkab_r3_hand',{p_request:k.id,p_student:student});await rpc('studkab_r3_return',{p_request:k.id,p_student:student,p_comment:'Нужны исправления'});const raw=(await db.query('select * from studkab_r3_work where request_id=$1',[k.id])).rows[0];assert.ok(raw.downloaded_at);
const rest=async path=>{const table=path.split('?')[0];if(table==='studkab_requests')return (await db.query('select * from studkab_requests where id=$1 and student_id=$2',[k.id,student])).rows;if(table==='studkab_r3_work')return [raw];if(table==='studkab_clarifications'||table==='studkab_r3_return_files')return [];if(table==='studkab_r3_returns')return (await db.query('select * from studkab_r3_returns where request_id=$1 order by n desc limit 1',[k.id])).rows;throw Error('Unexpected read '+path)};
const api=handler({auth:async()=>({id:student,email:'student@offline.test',email_confirmed_at:'yes'}),isMember:async id=>id===student,db:rest});const res=await api(new Request('https://offline.test',{method:'POST',headers:{authorization:'Bearer offline'},body:JSON.stringify({action:'student-progress',id:k.id})}));assert.equal(res.status,200);const body=await res.json();assert.ok(body.work.returnedAt);assert.equal(body.work.delivered,null);assert.equal(body.work.downloadedAt,null);assert.equal(body.work.handedAt,null);assert.equal(body.work.result,undefined);assert.equal(body.result,undefined);
});
