import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {randomUUID} from 'node:crypto';
import {setupAssistantBudgetFixture} from './assistant-budget-fixture.mjs';
const actor=randomUUID(),student=randomUUID(),other=randomUUID(),fingerprint='a'.repeat(64);let db;
before(async()=>{db=new PGlite();await setupAssistantBudgetFixture(db,{actor,student,other});});after(async()=>db?.close());
const rpc=async(n,a=[])=>(await db.query('select public.'+n+'('+a.map((_,i)=>'$'+(i+1)).join(',')+') value',a)).rows[0].value;
async function kit(sections=['answer']){const id=randomUUID();await db.query('insert into studkab_requests(id,student_id,payload) values($1,$2,$3)',[id,student,{route:'r3',n:'Offline Student',rq:'Full assignment'}]);const s=await rpc('studkab_assistant_snapshot',[id,actor]);const a=await rpc('studkab_assistant_accept',[id,actor,'deepseek',randomUUID(),1,fingerprint,s.basis,{schema:2},sections]);return {id,job:a.jobId};}
async function claim(k){const q=await rpc('studkab_assistant_quote',[k.job,actor,10000]);await rpc('studkab_assistant_confirm_queue',[k.job,actor,q.quoteId,10000]);return rpc('studkab_assistant_claim',[k.job,actor]);}
// Disposable database fixture only; never run against production or its settings.
async function budget(reserved=0,cap=1070000){await db.exec('reset role');await db.query('update studkab_gen_budget set limit_microusd=10000000,reserved_microusd=$1',[reserved]);await db.query('update studkab_gen_policy set temporary_total_microusd=$1',[cap]);await db.exec('set role service_role');}
const dispatch=(k,c,cost=10000)=>rpc('studkab_assistant_reserve_dispatch',[k.job,actor,c.claim,cost,'deepseek-flash']);
const response=(k,p)=>({status:'completed',jobId:k.job,requestId:k.id,provider:'deepseek',revision:1,fingerprint,dispatchId:p.dispatchId,sections:[{id:'answer',name:'Answer',text:'Full offline text'}]});
test('production-shaped exhausted policy reports zero; no attempt, start or budget mutation',async()=>{await budget();const k=await kit(),c=await claim(k);await budget(1157290);assert.equal((await rpc('studkab_assistant_budget',[actor])).remainingMicrousd,0);assert.deepEqual(await dispatch(k,c),{ok:false,reason:'budget',remainingMicrousd:0});assert.equal((await rpc('studkab_assistant_state',[k.id,actor])).job.startedAt,null);assert.equal((await db.query('select count(*) n from studkab_assistant_attempts')).rows[0].n,0);assert.equal((await db.query('select reserved_microusd from studkab_gen_budget')).rows[0].reserved_microusd,1157290);});
test('ledger mismatch, wrong model and old nonfinancial dispatch fail before payment',async()=>{await budget(100);const k=await kit(),c=await claim(k);await assert.rejects(()=>dispatch(k,c),/LEDGER_MISMATCH/);await assert.rejects(()=>rpc('studkab_assistant_reserve_dispatch',[k.job,actor,c.claim,10000,'claude']),/INVALID_RESERVE/);await assert.rejects(()=>rpc('studkab_assistant_dispatch',[k.job,actor,c.claim]),/FINANCIAL_DISPATCH_REQUIRED/);});
test('reservation and exact completion keep shared reserve and immutable receipt',async()=>{await budget();const k=await kit(),c=await claim(k),p=await dispatch(k,c);assert.equal(p.reservedMicrousd,10000);assert.equal(await rpc('studkab_intake_ledger_matches',[10000]),true);await assert.rejects(()=>dispatch(k,c),/STALE_CLAIM/);const wrong=response(k,p);wrong.dispatchId=randomUUID();await assert.rejects(()=>rpc('studkab_assistant_complete',[k.job,actor,c.claim,wrong]),/DISPATCH_RECEIPT_REQUIRED/);await rpc('studkab_assistant_complete',[k.job,actor,c.claim,response(k,p)]);const ret=await rpc('studkab_assistant_begin_return',[k.job,actor,1,fingerprint]);assert.equal((await rpc('studkab_assistant_recover_next',[actor])).recovery,false);await db.query("update studkab_assistant_jobs set return_lease_until=clock_timestamp()-interval '1 second' where id=$1",[k.job]);assert.equal((await rpc('studkab_assistant_recover_next',[actor])).jobId,k.job);await rpc('studkab_assistant_fail_return',[k.job,actor,ret.claim]);assert.equal((await db.query('select state from studkab_assistant_attempts where job_id=$1',[k.job])).rows[0].state,'done');assert.equal((await db.query('select reserved_microusd from studkab_gen_budget')).rows[0].reserved_microusd,10000);await assert.rejects(()=>db.query('update studkab_assistant_attempts set reservation_microusd=1 where job_id=$1',[k.job]),/IMMUTABLE_ASSISTANT_RESERVE/);});
test('unknown response retains funds, is terminal and cannot replay paid call',async()=>{const k=await kit(),c=await claim(k),p=await dispatch(k,c);await rpc('studkab_assistant_unknown',[k.job,actor,c.claim,p.dispatchId]);await rpc('studkab_assistant_unknown',[k.job,actor,c.claim,p.dispatchId]);await assert.rejects(()=>dispatch(k,c),/STALE_CLAIM/);await assert.rejects(()=>rpc('studkab_assistant_complete',[k.job,actor,c.claim,response(k,p)]),/UNCONFIRMED_RESULT/);assert.equal(await rpc('studkab_intake_ledger_matches',[20000]),true);});
test('source-bound server planning freezes once without a new manual confirmation gate',async()=>{const k=await kit([]);await assert.rejects(()=>rpc('studkab_assistant_queue',[k.job,actor]),/PLAN_REQUIRED/);await assert.rejects(()=>rpc('studkab_assistant_freeze_plan',[k.job,actor,1,fingerprint,['answer'],{}]),/SOURCE_PLAN_REQUIRED/);const ev={method:'server-source-plan',sourceFingerprint:fingerprint,readerVersion:'offline-reader-1',sourceRefs:['request.rq']};await rpc('studkab_assistant_freeze_plan',[k.job,actor,1,fingerprint,['answer'],ev]);await rpc('studkab_assistant_queue',[k.job,actor]);assert.equal((await rpc('studkab_assistant_state',[k.id,actor])).job.planReady,true);await assert.rejects(()=>rpc('studkab_assistant_freeze_plan',[k.job,actor,1,fingerprint,['other'],ev]),/PLAN_BINDING_CHANGED/);});
test('machine actor resolution and private RPC/table grants preserve role boundary',async()=>{assert.equal(await rpc('studkab_assistant_runner_actor'),actor);await assert.rejects(()=>rpc('studkab_assistant_budget',[student]),/FORBIDDEN/);await db.exec('set role authenticated');await assert.rejects(()=>rpc('studkab_assistant_runner_actor'),/permission denied/);await assert.rejects(()=>db.query('select * from studkab_assistant_attempts'),/permission denied/);await db.exec('set role service_role');});

test('exact frozen quote is required and cannot be tampered or silently re-priced',async()=>{const k=await kit();const q=await rpc('studkab_assistant_quote',[k.job,actor,10000]);await assert.rejects(()=>rpc('studkab_assistant_quote',[k.job,actor,11000]),/QUOTE_PRICE_CHANGED/);await assert.rejects(()=>rpc('studkab_assistant_confirm_queue',[k.job,actor,q.quoteId,9999]),/QUOTE_BINDING_CHANGED/);await rpc('studkab_assistant_queue',[k.job,actor]);const c=await rpc('studkab_assistant_claim',[k.job,actor]);await assert.rejects(()=>dispatch(k,c),/PAID_CONFIRMATION_REQUIRED/);});
test('request deletion removes source snapshot and planning but retains financial reservation',async()=>{const k=await kit([]),s=await rpc('studkab_assistant_snapshot',[k.id,actor]),op=randomUUID();await rpc('studkab_assistant_freeze_plan',[k.job,actor,1,fingerprint,['answer'],{method:'server-source-plan',sourceFingerprint:fingerprint,readerVersion:'offline-1',sourceRefs:['request.rq']}]);const alias=await rpc('studkab_assistant_accept',[k.id,actor,'deepseek',op,1,fingerprint,s.basis,{schema:2},[]]);assert.equal(alias.jobId,k.job);assert.equal((await rpc('studkab_assistant_accept',[k.id,actor,'deepseek',op,1,fingerprint,s.basis,{schema:2},[]])).duplicate,true);const c=await claim(k),p=await dispatch(k,c);await db.query('delete from studkab_requests where id=$1',[k.id]);assert.equal((await db.query('select count(*) n from studkab_assistant_jobs where id=$1',[k.job])).rows[0].n,0);assert.equal((await db.query('select count(*) n from studkab_assistant_quotes where job_id=$1',[k.job])).rows[0].n,0);assert.equal((await db.query('select count(*) n from studkab_assistant_plans where job_id=$1',[k.job])).rows[0].n,0);assert.equal((await db.query('select reservation_microusd from studkab_assistant_attempts where dispatch_id=$1',[p.dispatchId])).rows[0].reservation_microusd,10000);});
