import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {setupAssistantBudgetFixture} from './assistant-budget-fixture.mjs';
const actor=randomUUID(),student=randomUUID(),other=randomUUID(),hash='a'.repeat(64),resultHash='b'.repeat(64);let db;
const rpc=async(n,a=[])=>(await db.query('select public.'+n+'('+a.map((_,i)=>'$'+(i+1)).join(',')+') value',a)).rows[0].value;
const claim=async c=>(await db.query('select public.studkab_process_notification_claim($1) value',[c])).rows.map(r=>r.value);
before(async()=>{db=new PGlite();await setupAssistantBudgetFixture(db,{actor,student,other});await db.exec(`reset role;
 alter table auth.users add column email_confirmed_at timestamptz default now();
 alter table studkab_requests add column number integer default 7;
 alter table studkab_request_config add column notification_email text;
 create table studkab_members(user_id uuid primary key);
 create table studkab_push_subscriptions(id uuid primary key,user_id uuid,enabled boolean,subscription jsonb);
 create table studkab_telegram_setup(installed boolean,owner_chat_id bigint,bound_at timestamptz);
 insert into studkab_telegram_setup values(false,null,null);
 grant all on studkab_members,studkab_push_subscriptions,studkab_telegram_setup to service_role;`);await db.query('insert into studkab_members values($1),($2)',[actor,student]);await db.query('insert into studkab_push_subscriptions values($1,$2,true,$3)',[randomUUID(),actor,{endpoint:'https://offline.invalid/push'}]);await db.exec(readFileSync(new URL('../supabase/migrations/20261009021521_assistant_notifications.sql',import.meta.url),'utf8'));await db.exec('set role service_role');});
after(async()=>db?.close());
async function kit(){const id=randomUUID();await db.query('insert into studkab_requests(id,student_id,payload) values($1,$2,$3)',[id,student,{route:'r3',n:'Offline student',rq:'Full assignment'}]);const s=await rpc('studkab_assistant_snapshot',[id,actor]);const a=await rpc('studkab_assistant_accept',[id,actor,'claude',randomUUID(),1,hash,s.basis,{schema:2},['answer']]);return {id,job:a.jobId};}
async function returned(k){await rpc('studkab_assistant_queue',[k.job,actor]);const c=await rpc('studkab_assistant_claim',[k.job,actor]);await rpc('studkab_assistant_dispatch',[k.job,actor,c.claim]);await rpc('studkab_assistant_complete',[k.job,actor,c.claim,{status:'completed',jobId:k.job,requestId:k.id,provider:'claude',revision:1,fingerprint:hash,sections:[{id:'answer',text:'Offline output'}]}]);const r=await rpc('studkab_assistant_begin_return',[k.job,actor,1,hash]);await rpc('studkab_assistant_commit_return',[k.job,actor,r.claim,1,hash,'Work.docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document',1200,resultHash,'r3-results/'+k.id+'/'+resultHash]);}
test('capture/start/review do not replay sends; future returned event creates exact missing channels once',async()=>{const k=await kit();assert.equal((await db.query('select count(*) n from studkab_process_notifications')).rows[0].n,0);await returned(k);const rows=(await db.query('select kind,channel,recipient_id from studkab_process_notifications where request_id=$1',[k.id])).rows;assert.equal(rows.length,3);assert.deepEqual(rows.map(r=>r.channel).sort(),['email','push','telegram']);assert.ok(rows.every(r=>r.kind==='file_prepared'&&r.recipient_id===actor));await rpc('studkab_process_notify_enqueue',[k.id,actor,'file_prepared',k.job+':returned:1']);assert.equal((await db.query('select count(*) n from studkab_process_notifications where request_id=$1',[k.id])).rows[0].n,3);await rpc('studkab_assistant_review',[k.job,actor,resultHash]);assert.equal((await db.query('select count(*) n from studkab_process_notifications where request_id=$1',[k.id])).rows[0].n,3);});
test('unknown and pre-dispatch blocking create stable problem events without reexecuting jobs',async()=>{const k=await kit();await rpc('studkab_assistant_queue',[k.job,actor]);await rpc('studkab_assistant_claim',[k.job,actor]);await db.query("update studkab_assistant_jobs set state='unknown' where id=$1",[k.job]);await db.query("update studkab_assistant_jobs set state='unknown' where id=$1",[k.job]);assert.equal((await db.query("select count(*) n from studkab_assistant_events where job_id=$1 and kind='problem'",[k.job])).rows[0].n,1);assert.equal((await db.query("select count(*) n from studkab_process_notifications where request_id=$1 and kind='problem'",[k.id])).rows[0].n,3);const b=await kit();await rpc('studkab_assistant_queue',[b.job,actor]);const c=await rpc('studkab_assistant_claim',[b.job,actor]);await rpc('studkab_assistant_fail_claim',[b.job,actor,c.claim]);assert.equal((await rpc('studkab_assistant_state',[b.id,actor])).job.state,'prepared');assert.equal((await db.query("select count(*) n from studkab_process_notifications where request_id=$1 and kind='problem'",[b.id])).rows[0].n,3);});
test('null or changed owner and arbitrary recipient never insert rows or abort work updates',async()=>{const k=await kit();await rpc('studkab_process_notify_enqueue',[k.id,null,'handed','null-owner']);await rpc('studkab_process_notify_enqueue',[k.id,other,'handed','arbitrary-owner']);await db.exec('update studkab_request_config set executor_email=null');await rpc('studkab_process_notify_enqueue',[k.id,actor,'handed','owner-unconfigured']);await db.query('insert into studkab_r3_work(request_id,student_id,handed_at) values($1,$2,now())',[k.id,student]);await db.query('update studkab_r3_work set handed_at=clock_timestamp() where request_id=$1',[k.id]);assert.equal((await db.query('select count(*) n from studkab_process_notifications where request_id=$1',[k.id])).rows[0].n,0);await db.exec("update studkab_request_config set executor_email='executor@offline.test'");});
test('claim leases have exact receipt; unknown and accepted are terminal, missing configuration may be retried',async()=>{const batch=await claim('email');assert.ok(batch.length>0&&batch.length<=5);const n=batch[0];assert.equal(n.email,null);assert.equal(await rpc('studkab_process_notification_finish',[n.id,randomUUID(),'accepted','wrong']),false);assert.equal(await rpc('studkab_process_notification_finish',[n.id,n.lease,'not_configured',null]),true);assert.equal(await rpc('studkab_process_notification_finish',[n.id,n.lease,'accepted','late']),false);await db.query('update studkab_process_notifications set retry_at=clock_timestamp() where id=$1',[n.id]);const retried=(await claim('email')).find(x=>x.id===n.id);assert.ok(retried);assert.equal(await rpc('studkab_process_notification_finish',[n.id,retried.lease,'unknown',null]),true);assert.ok(!(await claim('email')).some(x=>x.id===n.id));const tg=await claim('telegram');assert.ok(tg.length<=5);const t=tg[0];assert.equal(await rpc('studkab_process_notification_finish',[t.id,t.lease,'accepted','message-1']),true);assert.ok(!(await claim('telegram')).some(x=>x.id===t.id));});
test('expired notification leases become unknown without retrying transmission; disabled device cancels',async()=>{const pushes=await claim('push');assert.ok(pushes.length);await db.query("update studkab_process_notifications set lease_until=clock_timestamp()-interval '1 second' where id=$1",[pushes[0].id]);await claim('push');assert.equal((await db.query('select status from studkab_process_notifications where id=$1',[pushes[0].id])).rows[0].status,'unknown');const k=await kit();await rpc('studkab_process_notify_enqueue',[k.id,actor,'handed','disabled-device']);await db.exec('update studkab_push_subscriptions set enabled=false');assert.ok(!(await claim('push')).some(x=>x.requestId===k.id));assert.equal((await db.query("select status from studkab_process_notifications where request_id=$1 and channel='push'",[k.id])).rows[0].status,'cancelled');});
test('Telegram links expire, are one-use and bind no arbitrary recipient; public roles cannot call RPCs',async()=>{const token='c'.repeat(64);await assert.rejects(()=>rpc('studkab_telegram_link_create',[other,token]),/FORBIDDEN/);await rpc('studkab_telegram_link_create',[student,token]);assert.equal(await rpc('studkab_telegram_link_consume',[token,12345]),true);assert.equal(await rpc('studkab_telegram_link_consume',[token,12345]),false);const state=await rpc('studkab_process_notification_state',[student]);assert.equal(state.telegram.configured,true);assert.ok(!JSON.stringify(state).includes('12345'));await rpc('studkab_telegram_unlink',[student]);assert.equal((await rpc('studkab_process_notification_state',[student])).telegram.configured,false);await db.exec('set role authenticated');await assert.rejects(()=>rpc('studkab_process_notification_state',[student]),/permission denied/);await assert.rejects(()=>db.query('select * from studkab_telegram_links'),/permission denied/);await db.exec('set role service_role');});

test('owner nonce updates existing global recipient; unlink preserves bot and student recipients',async()=>{await db.exec('update studkab_telegram_setup set installed=true,owner_chat_id=88888,bound_at=clock_timestamp()');assert.equal((await rpc('studkab_process_notification_state',[actor])).telegram.configured,true);const st='d'.repeat(64),own='e'.repeat(64);await rpc('studkab_telegram_link_create',[student,st]);assert.equal(await rpc('studkab_telegram_link_consume',[st,88888]),false);assert.equal(await rpc('studkab_telegram_link_consume',[st,12345]),true);await rpc('studkab_telegram_link_create',[actor,own]);assert.equal(await rpc('studkab_telegram_link_consume',[own,12345]),false);assert.equal(await rpc('studkab_telegram_link_consume',[own,99999]),true);assert.equal((await db.query('select owner_chat_id from studkab_telegram_setup')).rows[0].owner_chat_id,99999);await rpc('studkab_telegram_unlink',[student]);assert.equal((await db.query('select owner_chat_id from studkab_telegram_setup')).rows[0].owner_chat_id,99999);await rpc('studkab_telegram_unlink',[actor]);assert.equal((await rpc('studkab_process_notification_state',[actor])).telegram.configured,false);const setup=(await db.query('select * from studkab_telegram_setup')).rows[0];assert.equal(setup.installed,true);assert.equal(setup.owner_chat_id,null);assert.equal(setup.bound_at,null);});

test('student answer adds exactly one enabled owner push and no duplicate existing Telegram path',async()=>{await db.exec('update studkab_push_subscriptions set enabled=true');const k=await kit(),question=randomUUID();await db.query('insert into studkab_clarifications(id,request_id,created_at) values($1,$2,clock_timestamp())',[question,k.id]);await db.query('update studkab_clarifications set answer=$1,answered_at=clock_timestamp() where id=$2',['Offline answer',question]);await rpc('studkab_process_notify_enqueue',[k.id,actor,'answer','r3-answer:'+question]);const rows=(await db.query("select channel,recipient_id from studkab_process_notifications where request_id=$1 and kind='answer'",[k.id])).rows;assert.deepEqual(rows.map(x=>x.channel).sort(),['email','push']);assert.ok(rows.every(x=>x.recipient_id===actor));});
