import test from 'node:test';
import assert from 'node:assert/strict';
import {collectAssistantBundle,digest} from '../supabase/functions/_shared/assistant-bundle.mjs';
import {prepareDeepseekAssistant,dispatchDeepseekAssistant} from '../supabase/functions/_shared/deepseek-assistant.mjs';
const R='11111111-1111-4111-8111-111111111111',F='22222222-2222-4222-8222-222222222222',J='33333333-3333-4333-8333-333333333333',C='44444444-4444-4444-8444-444444444444';
const bytes=new TextEncoder().encode('Полное задание');
async function kit(){return collectAssistantBundle({request:{id:R,revision:1,ready_at:'yes',payload:{route:'r3',k:'Практическая',d:'Экономика',n:'Студент',u:'Вуз'}},provider:'deepseek',attachmentsComplete:true,attachments:[{id:F,request_id:R,file_name:'Задание.txt',content_type:'text/plain',file_hash:await digest(bytes),size_bytes:bytes.length,storage_path:R+'/f'}],context:{answers:[{answer:'Исходные данные'}],passports:[],materialRevisions:[]}},{loadRequestFile:async()=>bytes});}
const readFile=async()=>({status:'ready',extracted_text:'Полный текст',blocks:[{text:'Полный текст',source:{paragraph:1}}],warnings:[],readerVersion:'test'});
test('DeepSeek preparation preserves every supplied context/file and reserves exact untruncated prompt',async()=>{const p=await prepareDeepseekAssistant(await kit(),['answer'],{readFile});const body=JSON.parse(p.user);assert.equal(body.context.answers[0].answer,'Исходные данные');assert.equal(body.files[0].text,'Полный текст');assert.equal(body.files[0].blocks.length,1);assert.equal(p.model,'deepseek-flash');assert.ok(p.estimatedMicrousd>0);});
test('unreadable/warned/tampered/oversized kit fails before budget reservation or provider request',async()=>{for(const read of [{status:'blocked'},await readFile(),{status:'ready',extracted_text:'a'.repeat(180001),warnings:[]}]){if(read.blocks)read.warnings=[{code:'unreadable'}];let calls=0;await assert.rejects(dispatchDeepseekAssistant(await kit(),J,C,['answer'],{readFile:async()=>read,proxyToken:'offline-test',reserveAndDispatch:async()=>{calls++},fetchProxy:async()=>{calls++}}),/MATERIAL_READING_INCOMPLETE|CONTEXT_TOO_BIG/);assert.equal(calls,0);}const b=await kit();b.files[0].bytes=new Uint8Array(bytes.length);await assert.rejects(prepareDeepseekAssistant(b,['answer'],{readFile}),/FILE_BYTES_REQUIRED/);});
test('existing proxy request occurs once only after atomic numerical reserve receipt and checks correlation/terminal result',async()=>{const b=await kit();let count=0;const fetchProxy=async(url,opts)=>{count++;assert.equal(url,'https://calm-bird-dae8.bf6mhynzgm.workers.dev');const q=JSON.parse(opts.body);assert.equal(q.client_request_id,C);assert.equal(q.provider,'deepseek');return {ok:true,json:async()=>({complete:true,client_request_id:C,detail:{reason:'stop'},text:JSON.stringify({sections:[{id:'answer',name:'Решение',text:'Решение по документам'}]})})}};const result=await dispatchDeepseekAssistant(b,J,C,['answer'],{readFile,proxyToken:'offline-test',reserveAndDispatch:async q=>({ok:true,dispatchId:C,reservedMicrousd:q.estimatedMicrousd}),fetchProxy});assert.equal(count,1);assert.equal(result.fingerprint,b.fingerprint);assert.equal(result.status,'completed');
await assert.rejects(dispatchDeepseekAssistant(b,J,C,['answer'],{readFile,proxyToken:'offline-test',reserveAndDispatch:async()=>({ok:true,dispatchId:C}),fetchProxy}),/BUDGET_NOT_CONFIRMED/);assert.equal(count,1);
});
test('lost provider reply does not retry paid inference',async()=>{let count=0;await assert.rejects(dispatchDeepseekAssistant(await kit(),J,C,['answer'],{readFile,proxyToken:'offline-test',reserveAndDispatch:async q=>({ok:true,dispatchId:C,reservedMicrousd:q.estimatedMicrousd}),fetchProxy:async()=>{count++;throw Error('NETWORK_LOST')}}),/NETWORK_LOST/);assert.equal(count,1);});
