import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {clarificationAction} from '../supabase/functions/studkab-requests/clarifications.mjs';
const student='11111111-1111-4111-8111-111111111111',executor='22222222-2222-4222-8222-222222222222',stranger='33333333-3333-4333-8333-333333333333';
const request='44444444-4444-4444-8444-444444444444',question='55555555-5555-4555-8555-555555555555';
const file=name=>fs.readFileSync(new URL('../supabase/migrations/'+name,import.meta.url),'utf8');
test('C120 dialogue events are atomic, unique and scoped to the recipient',async()=>{
 const db=new PGlite();
 try{
  await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
   create schema auth; create table auth.users(id uuid primary key,email text);
   create table studkab_request_config(executor_email text);
   create table studkab_members(user_id uuid primary key);
   create table studkab_requests(id uuid primary key,student_id uuid,deleting_at timestamptz);
   insert into auth.users values('${student}','student@example.test'),('${executor}','executor@example.test'),('${stranger}','stranger@example.test');
   insert into studkab_request_config values('executor@example.test');
   insert into studkab_members values('${student}');
   insert into studkab_requests values('${request}','${student}',null);
  `);
  for(const name of ['20260914105509_studkab_requirement_passports.sql','20260921165603_c084_requirement_clarifications.sql','20260921181451_c085_clarification_actor_permissions.sql','20260926114639_c120_dialog_events.sql'])await db.exec(file(name));
  await db.exec(`create table studkab_push_subscriptions(id uuid primary key);
   create table studkab_push_deliveries(key text primary key,subscription_id uuid references studkab_push_subscriptions(id),claimed_at timestamptz default now(),attempts integer default 1,sent_at timestamptz,result text);
   grant select,insert,update on studkab_push_deliveries to service_role;
   grant select,insert on studkab_push_subscriptions to service_role;`);
  const oldClaim=file('20260907113822_studkab_deadline_push.sql').match(/create function public\.claim_studkab_push_delivery\([\s\S]*?\$\$;/)[0];
  await db.exec(oldClaim);
  await db.exec('revoke all on function public.claim_studkab_push_delivery(text,uuid) from public,anon,authenticated; grant execute on function public.claim_studkab_push_delivery(text,uuid) to service_role;');
  await db.exec(file('20260926161000_c124_dialog_retry.sql'));
  await db.exec(`grant usage on schema auth to service_role;
   grant select,update on studkab_requests to service_role;
   grant select on studkab_request_config,studkab_members to service_role;set role service_role;`);
  const items=[{id:'METHODOLOGY',category:'method',required:true,verified:true,text:'Методика',source:'Файл',answer_ids:[]}];
  await db.query('select studkab_requirement_passport_save($1,$2,$3,$4,$5,$6)',[request,executor,'Требования','Проверка',JSON.stringify(items),'a'.repeat(64)]);
  const ask=()=>db.query('select studkab_clarification_ask($1,$2,$3,$4,$5)',[request,executor,question,'METHODOLOGY','Какую методику использовать?']);
  await ask();await ask();
  assert.deepEqual((await db.query('select kind,recipient_id from studkab_dialog_events')).rows.map(r=>[r.kind,r.recipient_id]),[['question',student]]);
  await assert.rejects(db.query('select studkab_clarification_answer($1,$2,$3,$4,$5)',[request,stranger,question,'Ответ','Файл']),/FORBIDDEN/);
  const answer=()=>db.query('select studkab_clarification_answer($1,$2,$3,$4,$5)',[request,student,question,'По заданию','Методичка, с. 2']);
  await answer();await answer();
  assert.deepEqual((await db.query('select kind,recipient_id from studkab_dialog_events order by id')).rows.map(r=>[r.kind,r.recipient_id]),[['question',student],['answer',executor]]);
  for(const role of ['anon','authenticated'])assert.equal((await db.query("select has_table_privilege($1,'studkab_dialog_events','SELECT') allowed",[role])).rows[0].allowed,false);
  for(const role of ['anon','authenticated']){
   assert.equal((await db.query("select has_function_privilege($1,'claim_studkab_dialog_telegram()','EXECUTE') allowed",[role])).rows[0].allowed,false);
   assert.equal((await db.query("select has_function_privilege($1,'claim_studkab_push_delivery(text,uuid)','EXECUTE') allowed",[role])).rows[0].allowed,false);
  }
  assert.equal((await db.query("select count(*)::int n from claim_studkab_dialog_telegram()")).rows[0].n,1);
  assert.equal((await db.query("select count(*)::int n from claim_studkab_dialog_telegram()")).rows[0].n,0);
  await db.query("update studkab_dialog_events set telegram_lease_until=now()-interval '1 minute' where kind='answer'");
  assert.equal((await db.query("select count(*)::int n from claim_studkab_dialog_telegram()")).rows[0].n,1);
  await db.query("update studkab_dialog_events set telegram_attempts=8,telegram_lease_until=now()-interval '1 minute',telegram_retry_at=now()-interval '1 minute' where kind='answer'");
  assert.equal((await db.query("select count(*)::int n from claim_studkab_dialog_telegram()")).rows[0].n,1);
  await db.query("update studkab_dialog_events set telegram_sent_at=now(),telegram_lease_until=now()-interval '1 minute' where kind='answer'");
  assert.equal((await db.query("select count(*)::int n from claim_studkab_dialog_telegram()")).rows[0].n,0);
  await db.query("update studkab_dialog_events set telegram_sent_at=null,read_at=now() where kind='answer'");
  assert.equal((await db.query("select count(*)::int n from claim_studkab_dialog_telegram()")).rows[0].n,0);
  const subscription='66666666-6666-4666-8666-666666666666';
  await db.query('insert into studkab_push_subscriptions(id) values($1)',[subscription]);
  const claim=key=>db.query('select claim_studkab_push_delivery($1,$2) ok',[key,subscription]);
  const dialogueKey=subscription+':dialog:1';
  assert.equal((await claim(dialogueKey)).rows[0].ok,true);
  await db.query("update studkab_push_deliveries set attempts=4,claimed_at=now()-interval '2 hours' where key=$1",[dialogueKey]);
  assert.equal((await claim(dialogueKey)).rows[0].ok,true);
  assert.equal((await claim(dialogueKey)).rows[0].ok,false);
  await db.query("update studkab_push_deliveries set attempts=12,claimed_at=now()-interval '2 hours' where key=$1",[dialogueKey]);
  assert.equal((await claim(dialogueKey)).rows[0].ok,true);
  await db.query("update studkab_push_deliveries set sent_at=now(),claimed_at=now()-interval '2 hours' where key=$1",[dialogueKey]);
  assert.equal((await claim(dialogueKey)).rows[0].ok,false);
  const reminderKey=subscription+':deadline:1';
  assert.equal((await claim(reminderKey)).rows[0].ok,true);
  await db.query("update studkab_push_deliveries set attempts=4,claimed_at=now()-interval '2 hours' where key=$1",[reminderKey]);
  assert.equal((await claim(reminderKey)).rows[0].ok,false);
  const calls=[];const deps={config:async()=>({executor_email:'executor@example.test'}),isMember:async()=>true,db:async(path,method,body)=>{
   calls.push({path,method,body});if(path.startsWith('studkab_requests?'))return path.includes('student_id=eq.'+stranger)?[]:[{id:request,student_id:student}];
   if(path.startsWith('studkab_dialog_events?')&&!method)return [{id:1,kind:'question'}];return [];
  }};
  assert.equal((await clarificationAction({action:'clarification-unread',id:request},{id:stranger,email:'stranger@example.test'},deps)).status,404);
  assert.equal((await clarificationAction({action:'clarification-unread',id:request},{id:student,email:'student@example.test'},deps)).data.question,1);
  await clarificationAction({action:'clarification-read',id:request},{id:student,email:'student@example.test'},deps);
  assert.match(calls.at(-1).path,new RegExp('recipient_id=eq\\.'+student));
 }finally{await db.close();}
});
