const {test}=require('node:test'),assert=require('node:assert/strict'),f=require('../financial-analysis.js');
const {fixture,material}=require('./fixtures/financial-synthetic.cjs');
test('20 metrics use end balances and averages with correct units',()=>{const r=f.calculate(fixture());assert.equal(r.metrics.length,20);const m=Object.fromEntries(r.metrics.map(m=>[m.name,m.values[0]]));assert.equal(m['Текущая ликвидность'],1.25);assert.equal(m['Автономия, %'],40);assert.equal(m['ROE, %'],25);assert.equal(m['Хранение запасов, дни'],365/3);assert.equal(m['Свободный поток, тыс. руб.'],10);assert.equal(r.dynamics[0].changes[0].absolute,0);});
test('missing opening balances, conflicting totals and blank values fail before calculation',()=>{const d=fixture();delete d.balance.equity;assert.throws(()=>f.calculate(d),/Нет корректных/);const e=fixture();e.balance.assets[2]++;assert.throws(()=>f.calculate(e),/Не сходится/);const t=material(fixture());assert.throws(()=>f.fromMaterials(t.replace('2022 | ','')),/годы/);assert.throws(()=>f.fromMaterials(t.replace('50 | 50',' | 50')),/Пустое/);assert.throws(()=>f.fromMaterials(t+'\nЧистая прибыль | 10 | 10 | 10'),/Повторная/);});
test('parser and scenario retain working capital and do not invent profit',()=>{const input=fixture(),r=f.fromMaterials(material(input)),s=r.scenarios[1];assert.equal(s.release,100/365*10);assert.equal(s.interestSaving,s.release*0.12);assert.equal(s.workingCapital,10);assert.equal(s.cash,10);assert.equal(s.equity,40);assert.equal(s.assets,100-s.release);assert(!('net' in s));assert(r.text.includes('Формулы и подстановка'));});
test('zero revenue yields null revenue ratios and unavailable scenario, not zero percent',()=>{const d=fixture();for(const k of Object.keys(d.income))d.income[k]=[0,0,0];d.cashflow.dividends=[0,0,0];d.cashflow.operating=[5,5,5];d.cashflow.financing=[0,0,0];const r=f.calculate(d);assert.deepEqual(r.metrics.find(m=>m.name==='Чистая рентабельность, %').values,[null,null,null]);assert(r.scenarios.every(s=>s.error));assert.equal(f.format(null),'не рассчитывается');});
test('unreconciled cash flows and oversized scenario are explicitly rejected',()=>{const d=fixture();d.cashflow.operating[0]++;assert.throws(()=>f.calculate(d),/операционный поток/);const e=fixture();e.balance.shortLoan=[0,0,0,0];e.balance.longLoan=[40,40,40,40];e.balance.shortLiabilities=[20,20,20,20];const r=f.calculate(e);assert(r.scenarios.every(s=>s.error));});

test('integration refuses mismatched compact input and provides deterministic context',()=>{
 const q=require('../draft-quality.js'),x={doc:{inputs:{requirements:'FIN-UAT-01',materials:material(fixture()),finance:'2023;100;50;40;20;40;100;10\n2024;100;50;40;20;40;100;10\n2025;100;50;40;20;40;100;10'}}};
 assert.equal(q.analysis(x).metrics.length,20);assert(q.context(x).includes('ROE, %'));x.doc.inputs.finance=x.doc.inputs.finance.replace('2024;100','2024;101');assert.throws(()=>q.analysis(x),/Баланс|не совпадает/);
});
