import test from 'node:test';import assert from 'node:assert/strict';
import {createNotificationChannels,channelPanel} from '../notification-channels-ui.mjs';
const valid={push:{configured:false},telegram:{configured:false},email:{configured:true},deliveries:[]};
function create(api,extra={}){return createNotificationChannels({api,active:()=>true,onChange:()=>{},openLink:()=>{},...extra});}
test('channel status begins unknown and only a full server observation confirms configured channels',async()=>{const s=create(async()=>valid);assert.match(channelPanel(s.state,true),/Не проверено/);await s.refresh();assert.equal(s.state.observed,true);assert.equal(s.state.channels.email,true);assert.equal(s.state.channels.telegram,false);assert.match(channelPanel(s.state,true),/Подключить Telegram/);});
test('Telegram link creates a real actionable URL but cannot mark Telegram configured',async()=>{const opened=[];const s=create(async i=>i.action==='notification-state'?valid:{url:'https://t.me/example_bot?start=synthetic',expiresAt:'2026-10-10T00:00:00Z'},{openLink:u=>opened.push(u)});await s.refresh();await s.telegram(true);assert.equal(s.state.channels.telegram,false);assert.equal(opened.length,1);assert.match(channelPanel(s.state,true),/href="https:\/\/t.me\/example_bot/);assert.match(s.state.message,/Старт/);});
test('late account callbacks do not publish private channel observations',async()=>{let active=true,finish;const paints=[];const s=create(()=>new Promise(r=>finish=r),{active:()=>active,onChange:v=>paints.push(v.message)});const pending=s.refresh();active=false;finish(valid);await pending;assert.equal(paints.length,1);assert.equal(s.state.channels,null);});
test('failed or malformed read removes confirmed status and duplicate clicks do not create links',async()=>{let fail=false,finish,count=0;const s=create(async i=>{if(i.action==='notification-state'){if(fail)throw Error('network');return valid;}count++;return new Promise(r=>finish=r);});await s.refresh();fail=true;await s.refresh();assert.equal(s.state.observed,false);const one=s.telegram(true);await s.telegram(true);assert.equal(count,1);finish({url:'https://attacker.example/link',expiresAt:'2026-10-10T00:00:00Z'});await one;assert.equal(s.state.linkUrl,null);assert.match(s.state.message,/Не удалось/);});
test('UI renders only channel/status from delivery records and never diagnostics or contact secrets',()=>{const html=channelPanel({observed:true,channels:{push:false,telegram:true,email:true},deliveries:[{channel:'email',status:'failed',secret:'PRIVATE_ADDRESS',error:'RAW_ERROR'}],message:''},true);assert.match(html,/Не отправлено/);assert.doesNotMatch(html,/PRIVATE_ADDRESS|RAW_ERROR/);});
