import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {setupSQL,actor,items,fingerprint} from './material-revision-fixture.mjs';
let db;const file='UEsDBHRlc3Q=';
const manifest={basis:'Задание',requirements:[{id:'task',label:'Задание',required:true,attachment_ids:[],answer_ids:[],payload_fields:['rq'],not_applicable_reason:''}]};
before(async()=>{db=new PGlite();await db.exec(setupSQL());for(const f of ['20260923082944_c098_material_manifest.sql','20260923120254_c099_test_delivery.sql'])await db.exec(readFileSync(new URL('../supabase/migrations/'+f,import.meta.url),'utf8'));await db.exec('set role service_role');});
after(async()=>await db?.close());
const one=async(sql,args=[])=>Object.values((await db.query(sql,args)).rows[0]||{})[0];
const rpc=(name,args)=>one('select '+name+'('+args.map((_,i)=>'$'+(i+1)).join(',')+')',args);
async function admin(sql,args=[]){await db.exec('reset role');try{return await db.query(sql,args);}finally{await db.exec('set role service_role');}}
const state=(q,a=actor.executor)=>rpc('studkab_test_delivery_context',[q,a,true]);
const read=(q,a=actor.student,include=false)=>rpc('studkab_test_result',[q,a,include]);
const send=(q,c,id=randomUUID(),a=actor.executor)=>rpc('studkab_test_deliver',[q,a,id,c.versionId,c.recipientId,c.fileHash,c.documentHash,c.passportId,c.sourceFingerprint]);
async function fixture(granted=true){const q=randomUUID();await db.query('insert into studkab_requests(id,student_id,client_id,payload) values($1,$2,$1::uuid::text,$3)',[q,actor.student,{id:q,rq:'Синтетическое задание'}]);const p=await rpc('studkab_requirement_passport_save',[q,actor.executor,'Паспорт','',items,fingerprint,null,manifest]);await rpc('studkab_requirement_passport_approve',[q,p.id,actor.executor,items,fingerprint,null,manifest]);const document={topic:'Synthetic',reviewContext:{passportId:p.id,sourceFingerprint:fingerprint,fingerprint:'b'.repeat(64)}};await rpc('prepare_studkab_result',[q,randomUUID(),actor.student,document,file]);if(granted)await admin("insert into studkab_test_request_grants(request_id,recipient_id,reason) values($1,$2,'Явно разрешённый синтетический маршрут')",[q,actor.student]);return {q,p,document,c:await state(q)};}
test('grant cannot be enabled by service_role, students or topic; null actor fails closed',async()=>{const {q}=await fixture(false);assert.equal((await state(q)).eligible,false);await assert.rejects(()=>db.query("insert into studkab_test_request_grants(request_id,recipient_id,reason) values($1,$2,'Недопустимое включение')",[q,actor.student]),/permission denied/);assert.equal((await rpc('studkab_test_delivery_context',[q,null,false])).reason,'FORBIDDEN');assert.equal((await state(q,actor.student)).reason,'FORBIDDEN');for(const role of ['anon','authenticated']){await db.exec('reset role;set role '+role);await assert.rejects(()=>state(q),/permission denied/);await db.exec('reset role;set role service_role');}});
test('separate test delivery preserves missing review and ordinary delivery gate',async()=>{const {q,c}=await fixture();assert.equal(c.eligible,true);const id=randomUUID(),d=await send(q,c,id);assert.equal(d.qualityStatus,'incomplete');assert.equal((await send(q,c,id)).deliveryId,id);assert.equal(await one('select count(*)::int from studkab_results where request_id=$1',[q]),0);assert.equal(await one('select count(*)::int from studkab_result_reviews where version_id=$1',[c.versionId]),0);const metadata=await read(q);assert.equal(metadata.testDelivery.docxBase64,undefined);assert.equal((await read(q,actor.student,true)).testDelivery.docxBase64,file);assert.match(metadata.testDelivery.label,/не завершена/);assert.equal((await read(q,actor.other)).error,'FORBIDDEN');assert.equal((await send(q,c,randomUUID(),actor.student)).error,'FORBIDDEN');const normal=await rpc('deliver_reviewed_studkab_result',[q,randomUUID(),c.versionId,randomUUID(),actor.student,c.fileHash,c.documentHash]);assert.equal(normal.error,'review_required');});
test('hash, operation collision and revoked grant cannot bypass on retry or read',async()=>{const a=await fixture(),b=await fixture(),id=randomUUID();assert.equal((await send(a.q,{...a.c,fileHash:'f'.repeat(64)})).error,'TEST_VERSION_CHANGED');await send(a.q,a.c,id);assert.equal((await send(b.q,b.c,id)).error,'TEST_OPERATION_CONFLICT');await admin('update studkab_test_request_grants set revoked_at=clock_timestamp() where request_id=$1',[a.q]);assert.equal((await read(a.q,actor.student,true)).error,'TEST_NOT_ALLOWED');assert.equal((await send(a.q,a.c,id)).error,'TEST_NOT_ALLOWED');});
test('new result version and changed passport revoke the old test bytes',async()=>{const {q,p,c,document}=await fixture();await send(q,c);await rpc('prepare_studkab_result',[q,randomUUID(),actor.student,document,file]);assert.equal((await read(q,actor.student,true)).error,'TEST_VERSION_CHANGED');assert.equal((await read(q,actor.executor,false)).testDelivery,null);assert.equal((await read(q,actor.executor,true)).error,'TEST_VERSION_CHANGED');const current=await state(q);await send(q,current);assert.equal((await read(q)).testDelivery.versionId,current.versionId);await rpc('studkab_requirement_passport_save',[q,actor.executor,'Новая версия','',items,fingerprint,null,manifest]);assert.equal((await read(q)).error,'MATERIAL_MANIFEST_REQUIRED');});
test('changed owner and revoked membership prohibit reading',async()=>{const a=await fixture();await send(a.q,a.c);await admin('update studkab_requests set student_id=$2 where id=$1',[a.q,actor.other]);assert.equal((await read(a.q,actor.student,true)).error,'FORBIDDEN');assert.equal((await read(a.q,actor.other,true)).error,'TEST_NOT_ALLOWED');const b=await fixture();await send(b.q,b.c);await admin('delete from studkab_members where user_id=$1',[actor.student]);assert.equal((await read(b.q,actor.student,true)).error,'FORBIDDEN');assert.equal((await state(b.q)).reason,'TEST_ACCESS_UNAVAILABLE');await admin('insert into studkab_members(user_id) values($1)',[actor.student]);});
test('prepared request deletion retains audit counts and no dangling test rows',async()=>{const {q,c,document}=await fixture();await send(q,c);await rpc('prepare_studkab_result',[q,randomUUID(),actor.student,document,file]);await db.exec("select set_config('request.jwt.claims','{\"role\":\"service_role\"}',false)");await rpc('prepare_studkab_request_delete',[q]);const r=await rpc('delete_studkab_request',[q,actor.executor,'Удаление синтетической проверки']);assert.equal(r.deleted,true);assert.equal(r.counts.testDeliveries,1);assert.equal(r.counts.testGrants,1);assert.equal(await one('select count(*)::int from studkab_test_deliveries where request_id=$1',[q]),0);assert.equal(await one('select count(*)::int from studkab_test_request_grants where request_id=$1',[q]),0);});

test('definer read context is pinned and private, delivery history immutable',async()=>{
 const p=(await db.query("select prosecdef,proconfig from pg_proc where oid='studkab_test_delivery_context(uuid,uuid,boolean)'::regprocedure")).rows[0];assert.equal(p.prosecdef,true);assert.ok(p.proconfig.some(x=>x.startsWith('search_path=')));
 const {q,c}=await fixture();await send(q,c);await assert.rejects(()=>db.query('update studkab_test_request_grants set revoked_at=null where request_id=$1',[q]),/permission denied/);
 await assert.rejects(()=>admin('update studkab_test_deliveries set quality_status=quality_status where request_id=$1',[q]),/IMMUTABLE/);
 await assert.rejects(()=>admin('delete from studkab_test_deliveries where request_id=$1',[q]),/IMMUTABLE/);
});
